#!/usr/bin/env python
import sys

from  eTraveler.clientAPI.connection import Connection
      
myConn = Connection('jrb', 'Raw', prodServer=False)
try: 
    boojumId = myConn.getManufacturerId(experimentSN='boojum-03', 
                                        htype='boojum')
    print 'Id for boojum-03 is: ', boojumId

    # Next line will now fail since it ran once successfully
    ret = myConn.setManufacturerId(experimentSN='applePie_001', 
                                   htype='applePie',
                                   manufacturerId='sous-chef-001')
    print 'Successfully set manufacturer id for applePie_001'

    # This one should fail
    ret = myConn.setManufacturerId(experimentSN='boojum-03', 
                                   htype='boojum',
                                   manufacturerId='already-set-01')
    sys.exit(0)
except Exception,msg:
    print 'Operation failed with exception: '
    print  msg
    sys.exit(1)

