#!/usr/bin/env python
import sys

from  eTraveler.clientAPI.connection import Connection

myConn = Connection('jrb', 'Raw', prodServer=False)
newId = ''
try: 
    newId=myConn.defineHardwareType(name='sprinkles', 
                                    description='type defined via eT API',
                                    batchedFlag=1,
                                    sequenceWidth='2')
    print 'New hardware type defined.  Returned id is ', newId
    sys.exit(0)
except Exception,msg:
    print 'Hardware type definition failed with exception ',msg
    sys.exit(1)

