#!/usr/bin/env python
from __future__ import print_function
import sys

from  eTraveler.clientAPI.connection import Connection
from  eTraveler.clientAPI.connection import ETClientAPINoDataException

myConn = Connection('jrb', 'Prod', 
                    debug=True, prodServer=True, appSuffix='')
#myConn = Connection('jrb', 'Dev', localServer=True, debug=True)
#myConn = Connection('jrb', 'Raw', prodServer=True)
rsp = {}
try:
    htype = 'LCA-11021_RTM'    #   run = 4248 also works
    experimentSN = 'LCA-11021_RTM-004'
    #labels = ['SnarkRandom:green']
    labels = ['Priority:', 'Mistake:']
    print("Calling getHardwareInstances for hardware type ", htype, " one label") 

    rsp = myConn.getHardwareNCRs(htype=htype, experimentSN=experimentSN,
                                      items='children',ncrLabels=labels)
    print("Returned list of NCRs for component ", experimentSN)
    entry = 0
    for h in rsp:
        print("for entry ",entry, " NCR# ", h['NCRnumber'])
        for k in h:
            print('Value for key ', k, ' is ',h[k])

    sys.exit(0)
except ETClientAPINoDataException as msg:
    print('No data exception: ',msg)
    sys.exit(1)
except Exception as msg:
    print('Operation failed with exception: ')
    print(msg)
    sys.exit(1)

