#!/usr/bin/env python
import sys

from  eTraveler.clientAPI.connection import Connection


myConn = Connection('jrb', 'Prod', prodServer=False, localServer=True,
                    debug=True, appSuffix='-jrb')
#myConn = Connection('jrb', 'Dev', prodServer=False, debug=True, appSuffix='-jrb')
#myConn = Connection('jrb', 'Dev', localServer=True, debug=True)
#myConn = Connection('jrb', 'Raw', prodServer=True)
rsp = {}
try:
    travelerName='SR-GEN-RCV-02'
    hardwareType='ITL-CCD'

    stepName='SR-RCV-02_Shipping_Documenation'
    #expSN='ITL-3800C-058'
    model='3800C'
    rsp = myConn.getManualResultsStep(travelerName=travelerName,
                                      stepName=stepName, model=model,
                                      hardwareType=hardwareType);
    # experimentSN=expSN,
    
    for cmp in rsp:
        print '\n\n**** Data for component ',cmp
        cmpdata = rsp[cmp]
        for k in cmpdata:
            if k != 'steps':
                print 'Value for key ',k, ' is ',cmpdata[k]
        steps = cmpdata['steps']
        for s in steps:
            print ('\nFor stepName %s' % (s) )
            iv = steps[s]
	    for iname in iv:
                print('\nGot data for input name %s' % (iname))
	        inp = iv[iname]
                for kk in inp:
                    print "For key '" + kk + "' value is: ", inp[kk]
    sys.exit(0)
except Exception,msg:
    print 'Operation failed with exception: '
    print  msg
    sys.exit(1)

