#!/usr/bin/env python
import sys

from  eTraveler.clientAPI.connection import Connection

myConn = Connection('jrb', 'Raw', prodServer=True)
newId = ''
try: 
    newId = myConn.registerHardware(htype='ITL-CCD', site='test',
                                    manufacturer='ITL',
                                    location='Cabinet', 
                                    experimentSN='ITL-CCD-675')
    print 'New hardware registered.  Returned id is ', newId
except Exception,msg:
    print 'Hardware registration failed with exception ',msg
    sys.exit(1)

try:
    myConn.runHarnessedById(hardwareId=newId, travelerName='jh_no-op-Generic',
                            hardwareGroup='Generic-CCD',
                            site='test', jhInstall='JoannesLaptopJH')
    print "Traveler execution succeeded"
except Exception,msg:
    print 'Traveler execution failed with exception ', msg
