#!/usr/bin/env python
import sys

from  eTraveler.clientAPI.connection import Connection

myConn = Connection('jrb', 'Raw', prodServer=True)
newId = ''
try: 
    newId = myConn.registerHardware(htype='ITL-CCD', site='test',
                                    manufacturer='ITL',
                                    location='Cabinet', 
                                    experimentSN='ITL-CCD-672')
    print 'New hardware registered.  Returned id is ', newId
except Exception,msg:
    print 'Hardware registration failed with exception ',msg


