#!/usr/bin/env python
from __future__ import print_function
import sys

from  eTraveler.clientAPI.connection import Connection

myConn = Connection('jrb', 'Raw', prodServer=True)

try:
    myConn.runHarnessed(experimentSN='ITL-CCD-666', 
                        htype='ITL-CCD',
                        travelerName='jh_no-op-Generic',
                        hardwareGroup='Generic-CCD',
                        site='test', jhInstall='JoannesLaptopJH')
    print("Traveler execution succeeded")
except Exception as msg:
    print('Traveler execution failed with exception ', msg)
