#!/usr/bin/env python
import sys

from  eTraveler.clientAPI.connection import Connection
from  eTraveler.clientAPI.connection import ETClientAPINoDataException

myConn = Connection('jrb', 'Raw', 
                    debug=True, prodServer=False, 
                    appSuffix='-jrb')
#myConn = Connection('jrb', 'Dev', localServer=True, debug=True)
#myConn = Connection('jrb', 'Raw', prodServer=True)
rsp = {}
try:
    htype = 'boojum'    #   run = 4248 also works
    print "Calling getHardwareInstances for hardware type ", htype

    rsp = myConn.getHardwareInstances(htype=htype)
    print "Returned lists of dicts for hardware type ", htype
    entry = 0
    for h in rsp:
        print "for entry ",entry, " experimentSN ", h['experimentSN']
        for k in h:
            print 'Value for key ', k, ' is ',h[k]

    sys.exit(0)
except ETClientAPINoDataException, msg:
    print 'No data exception: ',msg
    sys.exit(1)
except Exception,msg:
    print 'Operation failed with exception: '
    print  msg
    sys.exit(1)

