#!/usr/bin/env python
import sys

from  eTraveler.clientAPI.connection import Connection
from  eTraveler.clientAPI.connection import ETClientAPINoDataException

myConn = Connection('jrb', 'Dev', 
                    debug=True, prodServer=False, appSuffix='-jrb')
#myConn = Connection('jrb', 'Dev', localServer=True, debug=True)
#myConn = Connection('jrb', 'Raw', prodServer=True)
rsp = {}
try:
    activity = 23000
    run = '4248D'    #   run = 4248 also works
    print "Calling getActivity with activityId ",activity
    rsp = myConn.getActivity(activityId=activity)
    for k in rsp:
        print 'Value for key ',k, ' is ',rsp[k]

    print "Calling getRunActivities with run ", run
    rsp = myConn.getRunActivities(run=run)
    print "Entries for ",len(rsp), " activities"
    for a in rsp:
        for k in a:
            print 'Value for key ', k, ' is ', a[k]

    sys.exit(0)
except ETClientAPINoDataException, msg:
    print 'No data exception: ',msg
    sys.exit(1)
except Exception,msg:
    print 'Operation failed with exception: '
    print  msg
    sys.exit(1)

