#!/usr/bin/env python
import sys

from  eTraveler.clientAPI.connection import Connection


myConn = Connection('jrb', 'Dev', prodServer=False, appSuffix='-jrb')

rsp = {}
##htype='e2v-CCD'
htype='LCA-10307'
traveler='NCR'
##step = 'NCR_C_Final_disposition'
step = 'NCR_Approval'

print 'Invoking getMissingSignatures with no arguments '
#print 'htype=',htype, ' travelerName=',traveler, ' stepName=',step
#,' experimentSN=',eSN
try:
    rsp = myConn.getMissingSignatures()


    print 'Data returned for ',len(rsp), ' components'
    for esn in rsp:
        print ('For component %s \n' % (esn))
        esnData = rsp[esn]
        for r in esnData:
	    print 'For raid=', r
            
	    runData = esnData[r]
	    for k in runData:
                if k != 'steps':		
                    print k,' : ', runData[k]
                steps = runData['steps']
                for s in steps:
                    print ('For stepName %s \n' % (s) )
                    inforecords = steps[s]
                    for sreq in inforecords:
                        for field in sreq:
                            print field, ':', sreq[field]
            
    sys.exit(0)
except Exception,msg:
    print 'Operation failed with exception: '
    print  msg
    sys.exit(1)

