#!/usr/bin/env python
import sys

from  eTraveler.clientAPI.connection import Connection

myConn = Connection('jrb', 'Raw', prodServer=False)
newId = ''
try: 
    newId = myConn.registerHardware(htype='ITL-CCD', site='SLAC', location='Cabinet', experimentSN='ITL-CCD-666')
    print 'New hardware registered.  Returned id is ', newId
    sys.exit(0)
except Exception,msg:
    print 'Hardware registration failed with exception ',msg
    sys.exit(1)

## missing parameter
#try: 
#    myConn.registerHardware(htype='boojum', site='SLAC', location='Cabinet')
#    print 'New hardware registered.  Returned id is ', newId
#except Exception,msg:
#    print 'Hardware registration failed with exception ',msg

try:
    myConn.runHarnessed(hardwareId='23', travelerName='jh_no-op-Generic',
                        hardwareGroup='Generic-CCD',
                        site='test', jhInstall='JoannesLaptopJH')
    print "Traveler execution succeeded"
except Exception,msg:
    print 'Traveler execution failed with exception ', msg
