#!/usr/bin/env python
import sys

from  eTraveler.clientAPI.connection import Connection


myConn = Connection('jrb', 'Prod', prodServer=False, debug=True, appSuffix='-jrb')
#myConn = Connection('jrb', 'Dev', prodServer=False, debug=True, appSuffix='-jrb')
#myConn = Connection('jrb', 'Dev', localServer=True, debug=True)
#myConn = Connection('jrb', 'Raw', prodServer=True)
rsp = {}
try:
    #travelerName='CR-WFS-RCV-02'
    travelerName='SR-GEN-RCV-02'
    #hardwareType='ITL-Wavefront-CCD'
    hardwareType='ITL-CCD'
    #model='4400B'
    #stepName='CR-WFS-RCV-02_step1'
    #stepName='SR-RCV-02_Visual_Inspection'
    stepName='SR-RCV-02_Shipping_Documenation'
    expSN='ITL-3800C-058'
    rsp = myConn.getManualResultsStep(travelerName=travelerName,
                                      stepName=stepName, experimentSN=expSN,
                                      hardwareType=hardwareType);
    for cmp in rsp:
        print '\n\n**** Data for component ',cmp
        cmpdata = rsp[cmp]
        for k in cmpdata:
            if k != 'steps':
                print 'Value for key ',k, ' is ',cmpdata[k]
        steps = cmpdata['steps']
        for s in steps:
            print ('\nFor stepName %s' % (s) )
            iv = steps[s]
	    for iname in iv:
                print('\nGot data for input name %s' % (iname))
	        inp = iv[iname]
                for kk in inp:
                    print "For key '" + kk + "' value is: ", inp[kk]
    sys.exit(0)
except Exception,msg:
    print 'Operation failed with exception: '
    print  msg
    sys.exit(1)

