#!/usr/bin/env python
from __future__ import print_function
import sys

from  eTraveler.clientAPI.connection import Connection


myConn = Connection('jrb', 'Dev', localServer=False, debug=True)
#myConn = Connection('jrb', 'Raw', prodServer=True)
rsp = {}
try:
    #run = '4689D'
    run = 4689
    step = 'read_noise_raft'
    rsp = myConn.getRunFilepaths(run=run, stepName=step)

    for s in rsp:
        print('For stepName %s \n' % (s) )
        inforecords = rsp[s]
        print('Record 0: ')
        for field in inforecords[0]:
            print(field, ':', inforecords[0][field])
        if len(inforecords) > 1:
            print('\nRecord 1: ')
            for field in inforecords[1]:
                print(field, ':', inforecords[1][field])
    sys.exit(0)
except Exception as msg:
    print('Operation failed with exception: ')
    print(msg)
    sys.exit(1)

