#!/usr/bin/env python
import sys

from  eTraveler.clientAPI.connection import Connection


myConn = Connection('jrb', 'Raw', prodServer=False)
#myConn = Connection('jrb', 'Raw', prodServer=True)
rsp = []
try:
    act = 587
    rsp = myConn.getRunInfo(activityId=act)

    print('Results from getRunInfo for activity %d\n' % (act))
    for k in rsp:
        print ('For key %s returned value is %s\n' % (k, rsp[k]) )

    sys.exit(0)
except Exception,msg:
    print 'Operation failed with exception: '
    print  msg
    sys.exit(1)

