#!/usr/bin/env python
import sys

from  eTraveler.clientAPI.connection import Connection
      
myConn = Connection('jrb', 'Test', prodServer=False)
rsp = []
try: 
    rsp = myConn.getHardwareHierarchy(experimentSN='boojum-0001',
    	                              htype='boojum',
                                      noBatch='false')
    print "Results from getHardwareHierarchy unfiltered:"
    iDict = 0
    for d in rsp:
        print("Examining array element %d", iDict)
        for k in d:
            print('For key {0} value is {1}'.format(k, d[k]))
        iDict++

    rsp = myConn.getHardwareHierarchy(experimentSN='boojum-0001',
    	                              htype='boojum')
    print "Results from getHardwareHierarchy with noBatch filtering:"
    iDict = 0
    for d in rsp:
        print("Examining array element %d", iDict)
        for k in d:
            print('For key {0} value is {1}'.format(k, d[k]))
        iDict++

    sys.exit(0)
except Exception,msg:
    print 'Operation failed with exception: '
    print  msg
    sys.exit(1)

