#!/usr/bin/env python
from __future__ import print_function
import sys

from  eTraveler.clientAPI.connection import Connection
from  eTraveler.clientAPI.connection import ETClientAPINoDataException

#myConn = Connection('jrb', 'Dev', 
#                    debug=True, prodServer=False, appSuffix='-jrb')
myConn = Connection('jrb', 'Dev', 
                    debug=True, prodServer=True)
##myConn = Connection('jrb', 'Dev', debug=True, prodServer=True)
#myConn = Connection('jrb', 'Dev', localServer=True, debug=True)
#myConn = Connection('jrb', 'Raw', prodServer=True)
rsp = {}
try:
    activity = 23000
    run = '4248D'    #   run = 4248 also works
    print("Calling getActivity with activityId ",activity)
    rsp = myConn.getActivity(activityId=activity)
    for k in rsp:
        print('Value for key ',k, ' is ',rsp[k])

    print("Calling getRunActivities with run ", run)
    rsp = myConn.getRunActivities(run=run)
    print("Entries for ",len(rsp), " activities")
    for a in rsp:
        for k in a:
            print('Value for key ', k, ' is ', a[k])

    sys.exit(0)
except ETClientAPINoDataException as nodata:
    print('No data exception: ',nodata.args[0])
    sys.exit(1)
except Exception as ex:
    print('Operation failed with exception: ')
    print(ex.args[0])
    sys.exit(1)

