#!/usr/bin/env python
import sys

from  eTraveler.clientAPI.connection import Connection
      
myConn = Connection('jrb', 'Raw', prodServer=False)
try: 
    msg = myConn.setHardwareStatus(experimentSN='boojum-01', htype='boojum',
                                   status='REJECTED')
    
    print "Results from setHardwareStatus: ", msg
    msg = myConn.adjustHardwareLabel(experimentSN='boojum-02', htype='boojum',
                                     label='non-compliant', adding='true',
                                     reason='made me invisible')
    sys.exit(0)
except Exception,msg:
    print 'Operation failed with exception: '
    print  msg
    sys.exit(1)

